version: 3
services:
  postgres:
    container_name: postgres
    image: postgres:14
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: kratos
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
    ports:
      - "25432:5432"

volumes:
  postgres-data:
