// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: v1/catalog.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CreateBeerReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CreateBeerReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateBeerReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CreateBeerReqMultiError, or
// nil if none found.
func (m *CreateBeerReq) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateBeerReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	if len(errors) > 0 {
		return CreateBeerReqMultiError(errors)
	}

	return nil
}

// CreateBeerReqMultiError is an error wrapping multiple validation errors
// returned by CreateBeerReq.ValidateAll() if the designated constraints
// aren't met.
type CreateBeerReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateBeerReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateBeerReqMultiError) AllErrors() []error { return m }

// CreateBeerReqValidationError is the validation error returned by
// CreateBeerReq.Validate if the designated constraints aren't met.
type CreateBeerReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateBeerReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateBeerReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateBeerReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateBeerReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateBeerReqValidationError) ErrorName() string { return "CreateBeerReqValidationError" }

// Error satisfies the builtin error interface
func (e CreateBeerReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateBeerReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateBeerReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateBeerReqValidationError{}

// Validate checks the field values on CreateBeerReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CreateBeerReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateBeerReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateBeerReplyMultiError, or nil if none found.
func (m *CreateBeerReply) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateBeerReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	if len(errors) > 0 {
		return CreateBeerReplyMultiError(errors)
	}

	return nil
}

// CreateBeerReplyMultiError is an error wrapping multiple validation errors
// returned by CreateBeerReply.ValidateAll() if the designated constraints
// aren't met.
type CreateBeerReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateBeerReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateBeerReplyMultiError) AllErrors() []error { return m }

// CreateBeerReplyValidationError is the validation error returned by
// CreateBeerReply.Validate if the designated constraints aren't met.
type CreateBeerReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateBeerReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateBeerReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateBeerReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateBeerReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateBeerReplyValidationError) ErrorName() string { return "CreateBeerReplyValidationError" }

// Error satisfies the builtin error interface
func (e CreateBeerReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateBeerReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateBeerReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateBeerReplyValidationError{}

// Validate checks the field values on GetBeerReq with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetBeerReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetBeerReq with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetBeerReqMultiError, or
// nil if none found.
func (m *GetBeerReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetBeerReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return GetBeerReqMultiError(errors)
	}

	return nil
}

// GetBeerReqMultiError is an error wrapping multiple validation errors
// returned by GetBeerReq.ValidateAll() if the designated constraints aren't met.
type GetBeerReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetBeerReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetBeerReqMultiError) AllErrors() []error { return m }

// GetBeerReqValidationError is the validation error returned by
// GetBeerReq.Validate if the designated constraints aren't met.
type GetBeerReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetBeerReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetBeerReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetBeerReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetBeerReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetBeerReqValidationError) ErrorName() string { return "GetBeerReqValidationError" }

// Error satisfies the builtin error interface
func (e GetBeerReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetBeerReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetBeerReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetBeerReqValidationError{}

// Validate checks the field values on GetBeerReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetBeerReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetBeerReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetBeerReplyMultiError, or
// nil if none found.
func (m *GetBeerReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetBeerReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	if len(errors) > 0 {
		return GetBeerReplyMultiError(errors)
	}

	return nil
}

// GetBeerReplyMultiError is an error wrapping multiple validation errors
// returned by GetBeerReply.ValidateAll() if the designated constraints aren't met.
type GetBeerReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetBeerReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetBeerReplyMultiError) AllErrors() []error { return m }

// GetBeerReplyValidationError is the validation error returned by
// GetBeerReply.Validate if the designated constraints aren't met.
type GetBeerReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetBeerReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetBeerReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetBeerReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetBeerReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetBeerReplyValidationError) ErrorName() string { return "GetBeerReplyValidationError" }

// Error satisfies the builtin error interface
func (e GetBeerReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetBeerReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetBeerReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetBeerReplyValidationError{}
