// Code generated by Caisin. DO NOT EDIT.
// source: apps/core/internal/data/ent/schema/user.go

package convert

import (
	v1 "kratos-base/api/user/v1"
	"kratos-base/internal/data/ent"
)
func UserUpdateReq2Data(v *v1.UserUpdateReq) *ent.User {
	if v == nil {
		return nil
	}
	return &ent.User{
		ID:       v.Id,
		Age:       v.Age,

	}
}


func UserData2UpdateReq(v *ent.User) *v1.UserUpdateReq {
	if v == nil {
		return nil
	}
	return &v1.UserUpdateReq{
		Id:       v.ID,
		Age:       v.Age,

	}
}

func UserData2Reply(v *ent.User) *v1.UserData {
	if v == nil {
		return nil
	}
	return &v1.UserData{
		Id:       v.ID,
		Age:       v.Age,
		Name:       v.Name,

	}
}

