// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"kratos-base/app/catalog/service/internal/data/ent/beer"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Beer is the model entity for the Beer schema.
type Beer struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name         string `json:"name,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Beer) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case beer.FieldID:
			values[i] = new(sql.NullInt64)
		case beer.FieldName:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Beer fields.
func (b *Beer) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case beer.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			b.ID = int64(value.Int64)
		case beer.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				b.Name = value.String
			}
		default:
			b.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Beer.
// This includes values selected through modifiers, order, etc.
func (b *Beer) Value(name string) (ent.Value, error) {
	return b.selectValues.Get(name)
}

// Update returns a builder for updating this Beer.
// Note that you need to call Beer.Unwrap() before calling this method if this Beer
// was returned from a transaction, and the transaction was committed or rolled back.
func (b *Beer) Update() *BeerUpdateOne {
	return NewBeerClient(b.config).UpdateOne(b)
}

// Unwrap unwraps the Beer entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (b *Beer) Unwrap() *Beer {
	_tx, ok := b.config.driver.(*txDriver)
	if !ok {
		panic("ent: Beer is not a transactional entity")
	}
	b.config.driver = _tx.drv
	return b
}

// String implements the fmt.Stringer.
func (b *Beer) String() string {
	var builder strings.Builder
	builder.WriteString("Beer(")
	builder.WriteString(fmt.Sprintf("id=%v, ", b.ID))
	builder.WriteString("name=")
	builder.WriteString(b.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Beers is a parsable slice of Beer.
type Beers []*Beer
