// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BeersColumns holds the columns for the "beers" table.
	BeersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString},
	}
	// BeersTable holds the schema information for the "beers" table.
	BeersTable = &schema.Table{
		Name:       "beers",
		Columns:    BeersColumns,
		PrimaryKey: []*schema.Column{BeersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BeersTable,
	}
)

func init() {
}
